### ISSUE TITLE
Not loading via Composer

### ISSUE THREAD

**Issue by psycl0n** [buuum/typeform#1]
This wrapper looks good, but it ´s not loading using composer. 
if you can just fix it.

**Comment by buuum** [comment]
Hi,

you can use Composer:

Typeform is available on Packagist and can be installed using Composer:
composer require buuum/typeform

**Comment by psycl0n** [comment]
Fatal error: Class 'Typeform' not found in /home/ubuntu/workspace/teste/teste.php on line 8

It´s not working on composer, even requiring:

require 'vendor/autoload.php';
